/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import utilities.Level;
import utilities.ReadingFromWeb;

/**
 *
 * @author Ad
 */
public class ResultCompareMainForm extends javax.swing.JFrame {

    /**
     * Creates new form ResultCompareMainForm
     */
    public ResultCompareMainForm() {
        initComponents();
        prepareComponents();
        showKetqua();
        pack();
    }

    private void prepareComponents() {
        DefaultComboBoxModel ketquaModel = (DefaultComboBoxModel) cbbKetqua.getModel();
        ketquaModel.addElement("Xổ Số Miền Bắc");
        cbbKetqua.setModel(ketquaModel);
        DefaultComboBoxModel ngayModel = (DefaultComboBoxModel) cbbNgay.getModel();
        for (int i = 1; i < 32; i++) {
            ngayModel.addElement(i);
        }
        cbbNgay.setModel(ngayModel);
        DefaultComboBoxModel thangModel = (DefaultComboBoxModel) cbbThang.getModel();
        for (int i = 1; i < 13; i++) {
            thangModel.addElement(i);
        }
        cbbThang.setModel(thangModel);
        DefaultComboBoxModel namModel = (DefaultComboBoxModel) cbbNam.getModel();
        for (int i = 2010; i < 2015; i++) {
            namModel.addElement(i);
        }
        cbbNam.setModel(namModel);
        btnTransparent1.setOpaque(false);
        btnTransparent1.setContentAreaFilled(false);
        btnTransparent1.setBorderPainted(false);
        btnTransparent2.setOpaque(false);
        btnTransparent2.setContentAreaFilled(false);
        btnTransparent2.setBorderPainted(false);
        
        Calendar calendar=Calendar.getInstance();
        calendar.add(Calendar.DAY_OF_MONTH, -1);
        int day=calendar.get(Calendar.DATE);
        int month=calendar.get(Calendar.MONTH);
        int year=calendar.get(Calendar.YEAR);
       
        cbbNgay.setSelectedItem(day);
        cbbThang.setSelectedItem(month+1);
        cbbNam.setSelectedItem(year);
    }

    private void showKetqua() {
        String ketqua = cbbKetqua.getSelectedItem().toString();
        String ngay = cbbNgay.getSelectedItem().toString();
        String thang = cbbThang.getSelectedItem().toString();
        String nam = cbbNam.getSelectedItem().toString();
        String date = ngay + "-" + thang + "-" + nam;
        ReadingFromWeb rfw = new ReadingFromWeb(date);
        result = rfw.getLevelsOfDay();
        DefaultTableModel dtm = (DefaultTableModel) tblKetqua.getModel();
        dtm.getDataVector().removeAllElements();
        if (result != null) {
            for (Level level : result) {
                dtm.addRow(new String[]{level.getLevel(), level.getResult()});
            }
            btnSoKetqua.setEnabled(true);
        } else {
            dtm.addRow(new String[]{"", "Không có kết quả!"});
            btnSoKetqua.setEnabled(false);
        }
        tblKetqua.setModel(dtm);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCheckPoint1 = new javax.swing.JPanel();
        btnTransparent2 = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        pnlCheckPoint2 = new javax.swing.JPanel();
        btnTransparent1 = new javax.swing.JButton();
        lblKetqua = new javax.swing.JLabel();
        cbbKetqua = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbbNgay = new javax.swing.JComboBox();
        lblThang = new javax.swing.JLabel();
        cbbThang = new javax.swing.JComboBox();
        lblNam = new javax.swing.JLabel();
        cbbNam = new javax.swing.JComboBox();
        btnXemKetqua = new javax.swing.JButton();
        spKetqua = new javax.swing.JScrollPane();
        tblKetqua = new javax.swing.JTable();
        btnSoKetqua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTransparent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransparent2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCheckPoint1Layout = new javax.swing.GroupLayout(pnlCheckPoint1);
        pnlCheckPoint1.setLayout(pnlCheckPoint1Layout);
        pnlCheckPoint1Layout.setHorizontalGroup(
            pnlCheckPoint1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckPoint1Layout.createSequentialGroup()
                .addComponent(btnTransparent2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCheckPoint1Layout.setVerticalGroup(
            pnlCheckPoint1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCheckPoint1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTransparent2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHeader.setText("So Kết Quả Sổ Xố");

        btnTransparent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransparent1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCheckPoint2Layout = new javax.swing.GroupLayout(pnlCheckPoint2);
        pnlCheckPoint2.setLayout(pnlCheckPoint2Layout);
        pnlCheckPoint2Layout.setHorizontalGroup(
            pnlCheckPoint2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTransparent1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlCheckPoint2Layout.setVerticalGroup(
            pnlCheckPoint2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckPoint2Layout.createSequentialGroup()
                .addComponent(btnTransparent1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        lblKetqua.setText("Kết quả:");

        cbbKetqua.setActionCommand("");
        cbbKetqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbKetquaActionPerformed(evt);
            }
        });

        jLabel1.setText("Ngày:");

        lblThang.setText("Tháng:");

        lblNam.setText("Năm:");

        btnXemKetqua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXemKetqua.setText("Xem");
        btnXemKetqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemKetquaActionPerformed(evt);
            }
        });

        tblKetqua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ));
        spKetqua.setViewportView(tblKetqua);

        btnSoKetqua.setText("So kết quả");
        btnSoKetqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoKetquaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblThang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKetqua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbKetqua, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(btnXemKetqua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSoKetqua)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(spKetqua, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlCheckPoint1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlCheckPoint2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlCheckPoint1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlCheckPoint2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKetqua)
                            .addComponent(cbbKetqua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblThang)
                            .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNam)
                            .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXemKetqua)
                            .addComponent(btnSoKetqua))))
                .addGap(18, 18, 18)
                .addComponent(spKetqua, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemKetquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemKetquaActionPerformed
        // TODO add your handling code here:        
        showKetqua();        
    }//GEN-LAST:event_btnXemKetquaActionPerformed

    private void cbbKetquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbKetquaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbKetquaActionPerformed

    private void btnTransparent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransparent1ActionPerformed
        // TODO add your handling code here:
        this.visible = true;
    }//GEN-LAST:event_btnTransparent1ActionPerformed

    private void btnTransparent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransparent2ActionPerformed
        // TODO add your handling code here:
        if (visible) {
            ContentMainDialog cmd=new ContentMainDialog(this, visible);
        }
        this.visible = false;
    }//GEN-LAST:event_btnTransparent2ActionPerformed

    private void btnSoKetquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoKetquaActionPerformed
        // TODO add your handling code here:
        SoKetqua skq=new SoKetqua(this, true, result);
    }//GEN-LAST:event_btnSoKetquaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultCompareMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultCompareMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultCompareMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultCompareMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultCompareMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSoKetqua;
    private javax.swing.JButton btnTransparent1;
    private javax.swing.JButton btnTransparent2;
    private javax.swing.JButton btnXemKetqua;
    private javax.swing.JComboBox cbbKetqua;
    private javax.swing.JComboBox cbbNam;
    private javax.swing.JComboBox cbbNgay;
    private javax.swing.JComboBox cbbThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblKetqua;
    private javax.swing.JLabel lblNam;
    private javax.swing.JLabel lblThang;
    private javax.swing.JPanel pnlCheckPoint1;
    private javax.swing.JPanel pnlCheckPoint2;
    private javax.swing.JScrollPane spKetqua;
    private javax.swing.JTable tblKetqua;
    // End of variables declaration//GEN-END:variables
    private boolean visible = false;
    private ArrayList<Level> result;
}
