/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Customer;
import entities.So;
import entities.SoOfDay;
import entities.Table;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ad
 */
public class ViewTables extends javax.swing.JDialog {

    /**
     * Creates new form NewTable
     */
    public ViewTables(ContentMainDialog parent, boolean modal, ArrayList<Table> tables, ArrayList<Customer> khach) {
        super(parent, modal);
        this.parent = parent;
        this.tables = tables;
        this.khach = khach;
        initComponents();
        prepareComponents();
        showKetqua();
        this.setVisible(true);
    }

    private void prepareComponents() {
        DefaultComboBoxModel ngayModel = (DefaultComboBoxModel) cbbNgay.getModel();
        for (int i = 1; i < 32; i++) {
            ngayModel.addElement(i);
        }
        cbbNgay.setModel(ngayModel);
        DefaultComboBoxModel thangModel = (DefaultComboBoxModel) cbbThang.getModel();
        for (int i = 1; i < 13; i++) {
            thangModel.addElement(i);
        }
        cbbThang.setModel(thangModel);
        DefaultComboBoxModel namModel = (DefaultComboBoxModel) cbbNam.getModel();
        for (int i = 2010; i < 2015; i++) {
            namModel.addElement(i);
        }
        cbbNam.setModel(namModel);

        Calendar calendar = Calendar.getInstance();
//        calendar.add(Calendar.DAY_OF_MONTH, -1);
        int day = calendar.get(Calendar.DATE);
        int month = calendar.get(Calendar.MONTH);
        int year = calendar.get(Calendar.YEAR);

        cbbNgay.setSelectedItem(day);
        cbbThang.setSelectedItem(month + 1);
        cbbNam.setSelectedItem(year);

    }

    private void showKetqua() {
        String ngay = cbbNgay.getSelectedItem().toString();
        String thang = cbbThang.getSelectedItem().toString();
        String nam = cbbNam.getSelectedItem().toString();
        date = ngay + "-" + thang + "-" + nam;

        updateData(date);
    }

    private void updateData(String date) {
        DefaultTableModel dtm = (DefaultTableModel) tblKetqua.getModel();
        dtm.getDataVector().removeAllElements();
        for (Table table : tables) {
            if (table.getDate().equals(date)) {
                this.table = table;
                break;
            }
        }
        if ((table != null && table.getSo().size() > 0)) {
            listOfSo = new ArrayList<So>();
            listOfSo = table.getSo();
            ArrayList<SoOfDay> soList = new ArrayList<SoOfDay>();
            for (So so : table.getSo()) {
                boolean isSoExisted = false;
                for (SoOfDay soOfDay : soList) {
                    if (soOfDay.getSo().equals(so.getSo())) {
                        isSoExisted = true;
                        soOfDay.moreSo(so);
                        break;
                    }
                }
                if (!isSoExisted) {
                    SoOfDay sod = new SoOfDay(date, so.getSo());
                    sod.moreSo(so);
                    soList.add(sod);
                }
            }
            for (SoOfDay soOfDay : soList) {
                dtm.addRow(new String[]{soOfDay.getSo(), Integer.toString(soOfDay.getDiem())});
            }
        } else {
            dtm.addRow(new String[]{"", "Không có kết quả!"});
        }
        tblKetqua.setModel(dtm);
    }

    public void addNewSo(So so) {
        if (table != null) {
            table.addSo(so);
            updateData(date);
        } else {            
            parent.createTable(date);
            updateData(date);
            table.addSo(so);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnXemKetqua = new javax.swing.JButton();
        lblNgay = new javax.swing.JLabel();
        cbbNgay = new javax.swing.JComboBox();
        lblThang = new javax.swing.JLabel();
        cbbThang = new javax.swing.JComboBox();
        lblNam = new javax.swing.JLabel();
        cbbNam = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKetqua = new javax.swing.JTable();
        btnThemso = new javax.swing.JButton();
        btnXemchitiet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnXemKetqua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXemKetqua.setText("Xem");
        btnXemKetqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemKetquaActionPerformed(evt);
            }
        });

        lblNgay.setText("Ngày:");

        lblThang.setText("Tháng:");

        lblNam.setText("Năm:");

        tblKetqua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số", "Điểm"
            }
        ));
        jScrollPane1.setViewportView(tblKetqua);

        btnThemso.setText("Thêm số");
        btnThemso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemsoActionPerformed(evt);
            }
        });

        btnXemchitiet.setText("Xem chi tiết");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXemchitiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNgay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblThang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXemKetqua)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXemKetqua)
                    .addComponent(lblNgay)
                    .addComponent(cbbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThang)
                    .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNam)
                    .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnThemso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXemchitiet)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemKetquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemKetquaActionPerformed
        // TODO add your handling code here:
        showKetqua();
    }//GEN-LAST:event_btnXemKetquaActionPerformed

    private void btnThemsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemsoActionPerformed
        // TODO add your handling code here:
        ThemSo ts = new ThemSo(this, true, khach, date);
    }//GEN-LAST:event_btnThemsoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                NewTable dialog = new NewTable(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemso;
    private javax.swing.JButton btnXemKetqua;
    private javax.swing.JButton btnXemchitiet;
    private javax.swing.JComboBox cbbNam;
    private javax.swing.JComboBox cbbNgay;
    private javax.swing.JComboBox cbbThang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNam;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblThang;
    private javax.swing.JTable tblKetqua;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Table> tables;
    private Table table;
    private ContentMainDialog parent;
    private ArrayList<So> listOfSo;
    private ArrayList<Customer> khach;
    private String date;
}
